spring.application.name=business-intelligence-agent

server.port=8080

# ==========================
# Monday.com Configuration
# ==========================

monday.api.url=https://api.monday.com/v2

monday.api.token=  
monday.deals.board.id= 

monday.workorders.board.id= 

groq.api.key=  
groq.api.url=https://api.groq.com/openai/v1/chat/completions
